In [59]:
import pptk
>>> xyz = np.c_[np.arange(10), np.zeros(10), np.zeros(10)]
>>> scalars = np.arange(10)
>>> v = pptk.viewer(xyz, scalars)
>>> v.set(point_size=0.1)
>>> v.color_map('cool', scale=[0, 10])
# >>> v.color_map([[0, 0, 0], [1, 1, 1]])

In [3]:
import numpy as np
import torch

In [4]:
label_set = torch.randint(0,2,(100,20000))

In [14]:
labelweights, _ = np.histogram(label_set, range(3))
labelweights = labelweights.astype(np.float32)
labelweights = labelweights / np.sum(labelweights)
labelweights = np.power(np.amax(labelweights) / labelweights, 1 / 3.0)

In [8]:
labelweights

array([1.000074, 1.      ], dtype=float32)

In [15]:
labelweights

array([1.000074, 1.      ], dtype=float32)

In [37]:
a

array([10,  1,  2,  5,  6])

In [47]:
b = np.array([2,6,100])

In [48]:
b

array([  2,   6, 100])

In [49]:
np.intersect1d(b,a)

array([2, 6])

In [50]:
point_dict={}


In [51]:
point_dict[]=

TypeError: unhashable type: 'list'

In [34]:
b[a] = 1

In [35]:
b

array([0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])